# Generated by Django 3.0 on 2020-01-23 01:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('slug_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
