# Generated by Django 3.0 on 2019-12-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_producttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Brand', verbose_name='marca')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slug', models.SlugField()),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('in_stock', models.BooleanField(default=True, verbose_name='en stock')),
                ('tags', models.ManyToManyField(blank=True, to='main.ProductTag')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
            },
        ),
    ]
